#%RAML 1.0
title: CYCLOPS (CCLP) API
version: v1
protocols: [ HTTP, HTTPS ]
baseUri: https://github.com/indexdata/mod-cyclops/

documentation:
  - title: CYCLOPS (CCLP) API
    content: API calls to interact with the various CCMS commands
  - title: Overview
    content: !include overview.md

/cyclops:
  /tags:
    description: "Tags that can be applied to records in a set"
    get:
      description: "Return a list of all known tags"
      responses:
        200:
          body:
            application/json:
              type: !include tags-schema.json
              example: !include examples/show-tags-example.json
    post:
      description: "Create a new tag"
      body:
        application/json:
          type: !include tag-schema.json
          example: !include examples/tag-example.json
      responses:
        204:
          description: No content is returned.
  /filters:
    description: "Filters that can narrow down records within a set"
    get:
      description: "Return a list of all known filters"
      responses:
        200:
          body:
            application/json:
              type: !include filters-schema.json
              example: !include examples/show-filters-example.json
    post:
      description: "Create a new filter"
      body:
        application/json:
          type: !include filter-schema.json
          example: !include examples/filter-example.json
      responses:
        204:
          description: No content is returned.
  /sets:
    description: "Sets of objects (books, films, etc.)"
    get:
      description: "Return a list of the names of all known sets"
      responses:
        200:
          body:
            application/json:
              type: !include sets-schema.json
              example: !include examples/show-sets-example.json
    post:
      description: "Create a new set"
      body:
        application/json:
          type: !include set-schema.json
          example: !include examples/set-example.json
      responses:
        204:
          description: No content is returned.

    /{setName}:
      uriParameters:
        setName:
          description: The name of the set to retrieve from, modify, delete or tag
          type: string
          required: true
      get:
        description: "Retrieve elements of a set"
        queryParameters:
          fields:
            type: string
            required: true
            description: Either * (for all fields) or a comma-separated list
          cond:
            type: string
            required: false
            description: An SQL-like WHERE condition
          filter:
            type: string
            required: false
            description: The name of a filter to apply to the set
          tag:
            type: string
            required: false
            description: The name of a tag to which to restrict the retrieved objects
          omitTag:
            type: string
            required: false
            description: The name of a tag by which to exclude objects from the retrieved
          sort:
            type: string
            required: false
            description: a comma-separated list of fields to sort the objects on. The default order is undefined if this is not specified
          offset:
            type: number
            required: false
            description: number of objects that will be skipped and not returned as part of the result. This can be useful for retrieving objects one page of data a time. Note that 'sort' is required whenever this is used
          limit:
            type: string
            required: false
            description: a maximum number of objects that will be returned
        responses:
          200:
            body:
              application/json:
                type: !include retrieve-schema.json
                example: !include examples/retrieve-example.json
      delete:
        description: "Delete a set"
        responses:
          204:
            description: No content is returned.
      /add:
        post:
          description: "add objects to a set"
          body:
            application/json:
              type: !include addobjects-schema.json
              example: !include examples/addobject-example.json
          responses:
            204:
              description: No content is returned.
      /remove:
        post:
          description: "remove objects from a set"
          body:
            application/json:
              type: !include removeobjects-schema.json
              example: !include examples/removeobject-example.json
          responses:
            204:
              description: No content is returned.
      /tag:
        /{tagName}:
          uriParameters:
            tagName:
              description: The name of the tag to add or remove to object within the set. The path `/cyclops/sets/mike/tag/dino` represents the resource "the set of records that are tagged with `dino` in the set `mike`.
              type: string
              required: true
          post:
            description: "add tag to, or remove tag from, objects within in a set"
            body:
              application/json:
                type: !include addremovetag-schema.json
                examples:
                  add:
                    value: !include examples/addtag-example.json
                  remove:
                    value: !include examples/removetag-example.json
            responses:
              204:
                description: No content is returned.
